# Generated by Django 5.2.8 on 2025-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_signer_affiliation_ror_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='ai_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='declaration',
            name='author_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
