# Generated by Django 5.2.8 on 2026-01-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_declaration_ai_used_declaration_author_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='author_affiliation_ror_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='declaration',
            name='author_orcid',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name='declaration',
            name='author_orcid_verified',
            field=models.BooleanField(default=False),
        ),
    ]
