# Generated by Django 5.2.8 on 2026-02-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apikey_alter_declaration_human_review_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='author_orcid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='human_review_level',
            field=models.IntegerField(default=0),
        ),
    ]
